import sys
import os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

# Import the functions we need to test
import asyncio
import tempfile
from gradio_app_advanced import analyze_and_speak, analyze_image, generate_voice

def test_analyze_and_speak():
    """Test the analyze_and_speak function"""
    print("Testing analyze_and_speak function...")
    
    # Since we can't easily test with a real image, let's test the voice generation part directly
    # Test with sample text that would be generated by analyze_image
    sample_text = "This is a sample medical analysis report.\n\nSYMPTOMS: Patient has mild fever and headache.\n\nDIAGNOSIS: Likely viral infection.\n\nTREATMENT: Rest and hydration recommended.\n\nMEDICATIONS:\n1. Paracetamol 500mg - Take 1 tablet every 6 hours as needed for fever\n2. Drink plenty of fluids\n\nFOLLOW-UP: If symptoms persist for more than 3 days, consult a physician."
    
    language = "English"
    gender = "Male"
    
    print(f"Sample text length: {len(sample_text)} characters")
    print(f"Language: {language}")
    print(f"Gender: {gender}")
    
    # Test the generate_voice function directly
    audio_file = generate_voice(sample_text, language, gender)
    
    if audio_file:
        print(f"✓ Success! Audio file created at: {audio_file}")
        # Check file size
        file_size = os.path.getsize(audio_file)
        print(f"Audio file size: {file_size} bytes")
        # Clean up
        os.unlink(audio_file)
        print("✓ Cleaned up temporary file")
        return True
    else:
        print("✗ Failed to generate audio")
        return False

if __name__ == "__main__":
    result = test_analyze_and_speak()
    print(f"Test result: {result}")